### ISSUE TITLE
abiword problem

### ISSUE THREAD

**Issue by tony37** [sugarlabs/slider-puzzle-branch#1]
This activity needs abiword dependency to be removed comparable to solution for Jigsaw Puzzle activity. Without lessons the activity works on Ubuntu 16.04 sucrose version.

**Comment by quozl** [comment]
Fixed by @zeecoder606 in commit c540bcd8be2f2c94d8ff0f10113247ccc31a22d0.

**Comment by godiard** [comment]
Would be nice add the lessons to Help activity (like we did wit Poll activity lessons)

**Comment by zeeshank95** [comment]
Sure, I will add the lessons to the help activity.

**Comment by quozl** [comment]
Then delete them here.  :grin:
