### ISSUE TITLE
Traceback, global name 'gtk' is not defined

### ISSUE THREAD

**Issue by quozl** [sugarlabs/slider-puzzle-branch#4]
Logs contain

```
Traceback (most recent call last):
  File "/home/olpc/Activities/SliderPuzzle.activity/SliderPuzzleUI.py", line 478, in process_key
    gtk.main_quit()
NameError: global name 'gtk' is not defined
```

**Comment by rhl-bthr** [comment]
Fixed in 95aaa6d

**Comment by quozl** [comment]
@pro-panda, thanks, I missed that.

@iqraceme, you can save time by adding to your commit message or pull request "fixes #n", where n is the issue number, or "fixes URL" where URL points to the issue.  GitHub will then automatically add links between the issue and pull request, and close an issue when the pull request is merged or the patch committed.  Because I use history a lot, my practice is to use the pull request for trivial issues, and use the commit message for complex issues.

**Comment by cemeiq** [comment]
Ok. Will be careful with the commit message next time.
